### ISSUE TITLE
main_redhat: command not found

### ISSUE THREAD

**Issue by yipy0005** [NISP-GmbH/SLURM#1]
Hi,

I'm trying to install SLURM on my Rocky Linux 9.4 and I encountered the following error:

```
bash slurm_install.sh
###################################################
Welcome to the SLURM Installation Script
###################################################
The current Linux distribution is: redhat_based
##########################################################################
Do you want to enable Slurm accounting support? Possible answers: [yes/no]
##########################################################################
yes
slurm_install.sh: line 888: main_redhat: command not found
```

Could I get some guidance on this?

Thank you!

Best regards,
Yew Mun

**Comment by franciscopaniskaseker** [comment]
@yipy0005 Thank you for the report. I already fixed. I am testing in rocky linux 9.4 before release the fix. I will tell you when the code is released.

**Comment by franciscopaniskaseker** [comment]
@yipy0005 fix released. Thank for your report!

You can execute git pull to receive the update and proceed with the setup. I tested with Rock Linux 9.4 and is working.
