### ISSUE TITLE
Install SLURM on a local machine

### ISSUE THREAD

**Issue by yipy0005** [NISP-GmbH/SLURM#2]
Hi,

I was just wondering, are there any lines in the bash script that I should change if I'm installing SLURM on a local machine with 32 cores instead of a cluster?

Best regards,
Yew Mun

**Comment by franciscopaniskaseker** [comment]
@yipy0005 Ciao. 

May you need to adjust the slurm.conf to reflect your single machine:
```bash
NodeName=$HOST CPUs=32 State=UNKNOWN
PartitionName=test Nodes=$HOST Default=YES MaxTime=INFINITE State=UP
```
